### ISSUE TITLE
depends on aws-cfn-decompiler

### ISSUE THREAD

**Issue by dan-mcdonald** [dldinternet/aws-cfn-compiler.archived#1]
Doesn't work without aws-cfn-decompiler gem, yet it is specified as a dependency.

**Comment by dldinternet** [comment]
aws-cfn-decompiler depends on aws-cfn-compiler.
Adding the former to the gem spec creates infinite dependency loop. 
Suggestions welcome

**Comment by dan-mcdonald** [comment]
How about combining the two gems into one?

**Comment by dldinternet** [comment]
Hmmm ... That could make sense ... Will investigate.
